truncate table comments, bookings, items, requests, users restart identity cascade;

create table if not exists users (
    id bigint generated by default as identity not null primary key,
    name varchar(256) not null,
    email varchar(512) not null unique
);

create table if not exists requests (
    id bigint generated by default as identity not null primary key,
    description varchar(4096),
    requestor_id bigint references users(id)
);

create table if not exists items (
    id bigint generated by default as identity not null primary key,
    name varchar(256) not null,
    description varchar (4096),
    is_available boolean,
    owner_id bigint references users(id),
    request_id bigint references requests(id)
);

create table if not exists bookings (
    id bigint generated by default as identity not null primary key,
    start_date timestamp,
    end_date timestamp,
    item_id bigint references items(id),
    booker_id bigint references users(id),
    status varchar(32)
);

create table if not exists comments (
    id bigint generated by default as identity not null primary key,
    text varchar(4096),
    item_id bigint references users(id),
    author_id bigint references users(id)
);